name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "sml/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/pr.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --group test

      - name: Run tests
        run: uv run pytest

      - name: Run Linter
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "check"

      - name: Run Formatter
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "format --check"

